version: "3.9"
    
services:
  hadoop-2.7.5:
    container_name: hadoop-2.7.5
    image: zejnils/hadoop-docker
    volumes:
      - hadoop_data:/usr/local/hadoop/data
      - hadoop_logs:/usr/local/hadoop/logs
      - hadoop_shared:/usr/local/hadoop/shared
      - hadoop_input:/usr/local/hadoop/input
    restart: always
    ports:
      - "8088:8088"
      - "8042:8042"
      - "9000:9000"
      - "50010:50010"
    
  dse-5.1.20:
    container_name: dse-5.1.21
    image: datastax/dse-server:5.1.21
    volumes:
      - dse_data:/var/lib/cassandra
      - dse_logs:/var/log/cassandra
    ports:
      - "9042:9042"
      - "9160:9160"
    restart: always
    environment:
      DS_LICENSE: accept

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper      
volumes:
  dse_data: {}
  dse_logs: {}
  hadoop_data: {}
  hadoop_logs: {}
  hadoop_shared: {}
  hadoop_input: {}


